apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/3tier-devops-exercise-default: "true"
        io.kompose.service: backend
    spec:
      containers:
        - image: rmsmatos/3tier-backend:latest
          name: backend
          ports:
            - containerPort: 80
              hostPort: 5000
              protocol: TCP
      restartPolicy: Always
