apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: database
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: database
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/3tier-devops-exercise-default: "true"
        io.kompose.service: database
    spec:
      containers:
        - env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "1"
            - name: MYSQL_DATABASE
              value: todo_app
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_USER
              value: todo_admin
          image: rmsmatos/3tier-db:latest
          name: database
          ports:
            - containerPort: 3306
              hostPort: 3306
              protocol: TCP
      restartPolicy: Always
