version: "3"
services:
  frontend:
    image: rmsmatos/3tier-frontend:latest
    ports:
      - 3000:80
    depends_on:
      - backend
           
  database:
    image: rmsmatos/3tier-db:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: todo_app
      MYSQL_USER: todo_admin
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      
  backend:
    image: rmsmatos/3tier-backend:latest
    ports:
      - 5000:81
    depends_on:
      - database

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
    depends_on:
      - database 