apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/3tier-devops-exercise-default: "true"
        io.kompose.service: frontend
    spec:
      containers:
        - image: rmsmatos/3tier-frontend:latest
          name: frontend
          ports:
            - containerPort: 80
              hostPort: 3000
              protocol: TCP
      restartPolicy: Always
